---
- name: deploy app using tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy war to tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/ansib/target/mavenansibleapp.war"
        dest: "/opt/tomcat/webapps/mavenansibleapp.war"
        remote_src: no
    
    - name : restart tomacat 
      systemd:
        name: tomact
        state: restarted
